// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuFhnv0leIPXKHTD57Sa2k38IBPuYYKc',
    appId: '1:393308587235:android:b95d477f400a04032831d6',
    messagingSenderId: '393308587235',
    projectId: 'chess-e776e',
    databaseURL: 'https://chess-e776e-default-rtdb.firebaseio.com',
    storageBucket: 'chess-e776e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFmk8kqR8OcSLtT6Fk9LgjfTK-71-8oDw',
    appId: '1:393308587235:ios:3f3e930e074196bc2831d6',
    messagingSenderId: '393308587235',
    projectId: 'chess-e776e',
    databaseURL: 'https://chess-e776e-default-rtdb.firebaseio.com',
    storageBucket: 'chess-e776e.firebasestorage.app',
    iosBundleId: 'com.example.travelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFmk8kqR8OcSLtT6Fk9LgjfTK-71-8oDw',
    appId: '1:393308587235:ios:3f3e930e074196bc2831d6',
    messagingSenderId: '393308587235',
    projectId: 'chess-e776e',
    databaseURL: 'https://chess-e776e-default-rtdb.firebaseio.com',
    storageBucket: 'chess-e776e.firebasestorage.app',
    iosBundleId: 'com.example.travelmate',
  );
}
